name: CI

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}

    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2"]
        rails: ["6.1", "7.0"]
        continue-on-error: [false]
        exclude:
          - ruby: "3.2"
            rails: "6.1"

    runs-on: ubuntu-latest

    env:
      RAILS_VERSION: ${{ matrix.rails }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install bundle
        run: bundle install

      - name: Run tests
        run: bundle exec rake
        continue-on-error: ${{ matrix.continue-on-error }}
